version: '3.9'

services:
  web:
    build: .
    ports:
     - 8080:80
    volumes:
      - ./app:/code/app
    depends_on:
      - redis
      - worker

  worker:
    build: .
    command: bash -c "cd /code/src/worker && celery -A server_hosting worker -l INFO"
    volumes:
      - ./app:/code/app
      - ./images:/storage
    depends_on:
      - redis
      - rabbitmq
    
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  
  redis:
    image: redis
    ports:
      - 6379:6379